
def label = "cicd-nodejs-sample-u00-${env.BUILD_NUMBER}"

/* -------- functions ---------- */
def notifySlack(STATUS, COLOR) {
	//slackSend (channel: '#cicd-nodejs-sample-u00', color: COLOR, message: STATUS+" : " +  "${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL})")
}

notifySlack("STARTED", "#FFFF00")

podTemplate(
	label: label, 
	containers: [
		containerTemplate(name: "trivy", image: "aquasec/trivy", ttyEnabled: true, command: "cat"),
		containerTemplate(name: "kubectl", image: "lachlanevenson/k8s-kubectl", command: "cat", ttyEnabled: true),
		containerTemplate(name: "scanner", image: "newtmitch/sonar-scanner", ttyEnabled: true, command: "cat"),
		containerTemplate(name: 'podman', image: 'mgoltzsche/podman', ttyEnabled: true, command: 'cat', privileged: true)
	],
	//volume mount
	volumes: [
		hostPathVolume(hostPath: "/etc/containers/registries.conf.d/myharbor.conf", mountPath: "/etc/containers/registries.conf.d/myharbor.conf")
	]
) 
{
	node(label) {
		stage("Get Source") {
			git branch: 'main', url: 'https://github.com/hiondal/cicd-nodejs-sample.git'
        } 

		//-- Read pipeline.properties and setting variables
		def props = readProperties  file:"deployment/pipeline.properties"
		
		credentialRegistry=props["credentialRegistry"]
		registry=props["registry"]
		organization=props["organization"]
		repository=props["repository"]
		tag=props["tag"]
		namespace=props["namespace"]
		manifest=props["manifest"]
		selector_key=props["selector_key"]
		selector_val=props["selector_val"]
		def app_url = ""

		try {

			stage("Build Microservice image") {
				container("podman") {
					withCredentials([usernamePassword(
						credentialsId: "${credentialRegistry}",
						usernameVariable: 'USER',
						passwordVariable: 'PASSWORD'
						)]) {
						    sh 'echo user "$USER" pasword "$PASSWORD"'
						    //sh "podman login ${registry} --tls-verify=false --username ${USER} --password ${PASSWORD}"
						    sh "podman login ${registry} --username ${USER} --password ${PASSWORD}"
							sh "podman build -f ./deployment/Dockerfile -t ${registry}/${organization}/${repository}:${tag} ."
							sh "sleep 2"
							sh "podman push ${registry}/${organization}/${repository}:${tag}"
							sh "podman tag ${registry}/${organization}/${repository}:${tag} ${registry}/${organization}/${repository}:latest"
							sh "podman push ${registry}/${organization}/${repository}:latest"
						}
					}
				}

			stage("Image Vulnerability Scanning") {
				container("trivy"){
					sh "trivy image ${registry}/${organization}/${repository}:${tag}"	
				}
			}

			stage( "Clean Up Existing Deployments" ) {
				container("kubectl") {
					sh "kubectl delete deploy -n ${namespace} --selector=${selector_key}=${selector_val}"
				}
			}

			stage( "Deploy to Cluster" ) {
				container("kubectl") {
					sh "kubectl apply -f ${manifest} -n ${namespace}"
					sh "sleep 5"
					
					sh "kubectl get ingress -n ${namespace} --no-headers | awk \'{print \$3}\' > sh-result"
					app_url = readFile('sh-result').trim()
				}
			}

	        notifySlack("${currentBuild.currentResult}", "#00FF00")
	            
			echo "**** FINISH ALL STAGES : SUCCESS"
			echo " Home URL : http://${app_url}"
		
		} catch(e) {
			currentBuild.result = "FAILED"
            notifySlack("${currentBuild.currentResult}", "#FF0000")            
		}
	}
}

